#!/bin/bash
set -e

echo "Starting Vercel build..."

# Ensure react-native-css-interop cache exists
echo "Ensuring css-interop cache..."
CACHE_DIR="node_modules/react-native-css-interop/.cache"
CACHE_FILE="$CACHE_DIR/web.css"

# Create directory
mkdir -p "$CACHE_DIR"
echo "✓ Created cache directory: $CACHE_DIR"

# Create cache file with content
echo '/* NativeWind CSS Cache - Generated by build script */' > "$CACHE_FILE"
echo "✓ Created cache file: $CACHE_FILE"

# Verify file exists
if [ -f "$CACHE_FILE" ]; then
  echo "✓ Cache file verified: $(ls -lh $CACHE_FILE)"
else
  echo "✗ ERROR: Cache file was not created!"
  exit 1
fi

# Build web app
echo "Building Expo web app..."
EXPO_USE_METRO_WORKSPACE_ROOT=1 npx expo export --platform web --output-dir=dist-web 2>&1 | tail -20

# Build server
echo "Building backend server..."
pnpm build:server

echo "Build complete!"
ls -lah dist-web/ | head -20
